# Generated by Django 3.2.12 on 2022-04-01 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvionModele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, null=True)),
                ('ville', models.CharField(max_length=30, null=True)),
                ('num', models.IntegerField(max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Escadron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Avion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_avion', models.CharField(max_length=30)),
                ('date_service', models.DateField()),
                ('base', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BDD.base')),
                ('escadron', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BDD.escadron')),
                ('modele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BDD.avionmodele')),
            ],
        ),
    ]
